import { DEFAULT_TODAY_DASHBOARD_PAGE_LAYOUT_ID } from '@/page-layout/constants/DefaultTodayDashboardPageLayoutId';
import { type PageLayout } from '@/page-layout/types/PageLayout';
import {
  AggregateOperations,
  AxisNameDisplay,
  BarChartLayout,
  GraphOrderBy,
  PageLayoutTabLayoutMode,
  PageLayoutType,
  WidgetConfigurationType,
  WidgetType,
} from '~/generated-metadata/graphql';

// TODO: replace objectMetadataId values with real workspace metadata IDs once
//       the per-user DASHBOARD provisioning mutation (ensurePersonalDashboard)
//       is available from the backend.
const TODAY_TAB_ID = 'today-dashboard-tab-main';

export const DEFAULT_TODAY_DASHBOARD_PAGE_LAYOUT: PageLayout = {
  __typename: 'PageLayout',
  id: DEFAULT_TODAY_DASHBOARD_PAGE_LAYOUT_ID,
  name: 'Today',
  type: PageLayoutType.DASHBOARD,
  objectMetadataId: null,
  universalIdentifier: '00000000-0000-0000-0000-000000000001',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deletedAt: null,
  defaultTabToFocusOnMobileAndSidePanelId: null,
  tabs: [
    {
      __typename: 'PageLayoutTab',
      applicationId: '',
      id: TODAY_TAB_ID,
      isActive: true,
      title: 'Today',
      icon: 'IconSun',
      position: 0,
      layoutMode: PageLayoutTabLayoutMode.GRID,
      pageLayoutId: DEFAULT_TODAY_DASHBOARD_PAGE_LAYOUT_ID,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: null,
      widgets: [
        // ── Row 0: KPI metrics ──────────────────────────────────────────
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'today-widget-open-deals',
          isActive: true,
          pageLayoutTabId: TODAY_TAB_ID,
          title: 'Open Deals',
          type: WidgetType.GRAPH,
          objectMetadataId: null, // TODO: replace with opportunity objectMetadataId
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 0,
            rowSpan: 3,
            columnSpan: 4,
          },
          position: {
            __typename: 'PageLayoutWidgetGridPosition',
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 0,
            rowSpan: 3,
            columnSpan: 4,
          },
          configuration: {
            __typename: 'AggregateChartConfiguration',
            configurationType: WidgetConfigurationType.AGGREGATE_CHART,
            // TODO: replace with real fieldMetadataId for opportunity.id
            aggregateFieldMetadataId: '',
            aggregateOperation: AggregateOperations.COUNT,
            label: 'Open Deals',
            description: 'Number of currently open opportunities',
            suffix: undefined,
            prefix: undefined,
            format: undefined,
            displayDataLabel: true,
            filter: null,
            firstDayOfTheWeek: undefined,
            timezone: undefined,
            ratioAggregateConfig: undefined,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'today-widget-pipeline-value',
          isActive: true,
          pageLayoutTabId: TODAY_TAB_ID,
          title: 'Pipeline Value',
          type: WidgetType.GRAPH,
          objectMetadataId: null, // TODO: replace with opportunity objectMetadataId
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 4,
            rowSpan: 3,
            columnSpan: 4,
          },
          position: {
            __typename: 'PageLayoutWidgetGridPosition',
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 4,
            rowSpan: 3,
            columnSpan: 4,
          },
          configuration: {
            __typename: 'AggregateChartConfiguration',
            configurationType: WidgetConfigurationType.AGGREGATE_CHART,
            // TODO: replace with real fieldMetadataId for opportunity.amount
            aggregateFieldMetadataId: '',
            aggregateOperation: AggregateOperations.SUM,
            label: 'Pipeline Value',
            description: 'Total value of open opportunities',
            prefix: '$',
            suffix: undefined,
            format: undefined,
            displayDataLabel: true,
            filter: null,
            firstDayOfTheWeek: undefined,
            timezone: undefined,
            ratioAggregateConfig: undefined,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'today-widget-win-rate',
          isActive: true,
          pageLayoutTabId: TODAY_TAB_ID,
          title: 'Win Rate',
          type: WidgetType.GRAPH,
          objectMetadataId: null, // TODO: replace with opportunity objectMetadataId
          gridPosition: {
            __typename: 'GridPosition',
            row: 0,
            column: 8,
            rowSpan: 3,
            columnSpan: 4,
          },
          position: {
            __typename: 'PageLayoutWidgetGridPosition',
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 0,
            column: 8,
            rowSpan: 3,
            columnSpan: 4,
          },
          configuration: {
            __typename: 'AggregateChartConfiguration',
            configurationType: WidgetConfigurationType.AGGREGATE_CHART,
            // TODO: replace with real fieldMetadataId for closed-won ratio
            aggregateFieldMetadataId: '',
            aggregateOperation: AggregateOperations.COUNT,
            label: 'Win Rate',
            description: 'Percentage of opportunities closed as won',
            suffix: '%',
            prefix: undefined,
            format: undefined,
            displayDataLabel: true,
            filter: null,
            firstDayOfTheWeek: undefined,
            timezone: undefined,
            ratioAggregateConfig: undefined,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },

        // ── Row 3: Pipeline chart + My Tasks ──────────────────────────
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'today-widget-pipeline-by-stage',
          isActive: true,
          pageLayoutTabId: TODAY_TAB_ID,
          title: 'Pipeline by Stage',
          type: WidgetType.GRAPH,
          objectMetadataId: null, // TODO: replace with opportunity objectMetadataId
          gridPosition: {
            __typename: 'GridPosition',
            row: 3,
            column: 0,
            rowSpan: 6,
            columnSpan: 8,
          },
          position: {
            __typename: 'PageLayoutWidgetGridPosition',
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 3,
            column: 0,
            rowSpan: 6,
            columnSpan: 8,
          },
          configuration: {
            __typename: 'BarChartConfiguration',
            configurationType: WidgetConfigurationType.BAR_CHART,
            layout: BarChartLayout.VERTICAL,
            displayDataLabel: true,
            displayLegend: true,
            color: 'auto',
            // TODO: replace with real fieldMetadataId for opportunity.stage
            primaryAxisGroupByFieldMetadataId: '',
            // TODO: replace with real fieldMetadataId for opportunity.amount
            aggregateFieldMetadataId: '',
            aggregateOperation: AggregateOperations.SUM,
            primaryAxisOrderBy: GraphOrderBy.FIELD_POSITION_ASC,
            axisNameDisplay: AxisNameDisplay.NONE,
            timezone: undefined,
            firstDayOfTheWeek: undefined,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'today-widget-my-tasks',
          isActive: true,
          pageLayoutTabId: TODAY_TAB_ID,
          title: 'My Tasks',
          type: WidgetType.TASKS,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 3,
            column: 8,
            rowSpan: 6,
            columnSpan: 4,
          },
          position: {
            __typename: 'PageLayoutWidgetGridPosition',
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 3,
            column: 8,
            rowSpan: 6,
            columnSpan: 4,
          },
          configuration: {
            __typename: 'TasksConfiguration',
            configurationType: WidgetConfigurationType.TASKS,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },

        // ── Row 9: Deals needing attention + Recent Activity ──────────
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'today-widget-deals-needing-attention',
          isActive: true,
          pageLayoutTabId: TODAY_TAB_ID,
          title: 'Deals Needing Attention',
          type: WidgetType.RECORD_TABLE,
          objectMetadataId: null, // TODO: replace with opportunity objectMetadataId
          gridPosition: {
            __typename: 'GridPosition',
            row: 9,
            column: 0,
            rowSpan: 6,
            columnSpan: 6,
          },
          position: {
            __typename: 'PageLayoutWidgetGridPosition',
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 9,
            column: 0,
            rowSpan: 6,
            columnSpan: 6,
          },
          configuration: {
            __typename: 'RecordTableConfiguration',
            configurationType: WidgetConfigurationType.RECORD_TABLE,
            viewId: null,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
        {
          __typename: 'PageLayoutWidget',
          applicationId: '',
          id: 'today-widget-recent-activity',
          isActive: true,
          pageLayoutTabId: TODAY_TAB_ID,
          title: 'Recent Activity',
          type: WidgetType.TIMELINE,
          objectMetadataId: null,
          gridPosition: {
            __typename: 'GridPosition',
            row: 9,
            column: 6,
            rowSpan: 6,
            columnSpan: 6,
          },
          position: {
            __typename: 'PageLayoutWidgetGridPosition',
            layoutMode: PageLayoutTabLayoutMode.GRID,
            row: 9,
            column: 6,
            rowSpan: 6,
            columnSpan: 6,
          },
          configuration: {
            __typename: 'TimelineConfiguration',
            configurationType: WidgetConfigurationType.TIMELINE,
          },
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          deletedAt: null,
        },
      ],
    },
  ],
};
